import pandas as pd
data = {"Name":['Akshay','Anuj','Bhumi','Kirti','Rohan','Ravi','Piyush','Raj','Tiya','Shivani'],
        "Hindi_marks":[78,89,79,92,69,88,84,82,79,80],
        "English_marks":[82,80,72,74,86,90,82,82,95,93],
        "MAths_marks":[80,84,80,95,70,89,80,87,86,94],}
df = pd.DataFrame(data)
print("Student Marks in three subjects\n",df)
print("--------------------------------------")
min_marks=df.min(skipna=True,numeric_only=True)
print("Minimum marks in each subject\n", min_marks)
print("--------------------------------------")
max_marks=df.max(skipna=True,numeric_only=True)
print("Maximum marks in each subject\n", max_marks)
print("--------------------------------------")
mode_marks=df.mode(numeric_only=True)
print("Mode marks of each subject\n", mode_marks)
mean_marks=df.mean(skipna=None, numeric_only=True)
print("Mean marks of each subject\n", mean_marks)
print("--------------------------------------")
median_marks=df.median(skipna=None, numeric_only=True)
print("Meadin marks of each subject\n", median_marks)
print("--------------------------------------")
count_marks=df.count(numeric_only=True)
print("Total count of each subject\n", count_marks)
print("--------------------------------------")
sum_marks=df.sum(skipna=None, numeric_only=True)
print("Total sum of each subject\n", sum_marks)
print("--------------------------------------")
quantile_marks=df.quantile(q=[0.25,0.5,0.75,1.0])
print("Marks distribution in each subject by using Quantile\n", quantile_marks)
print("--------------------------------------")
var_marks=df.var(skipna=None, numeric_only=True)
print("Compute Variance marks of each subject\n", var_marks)
print("--------------------------------------")
